### ISSUE TITLE
Document and guard against cost pitfalls

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-console#174]
Functionality:
- [x] When starting a cluster, ensure that the chosen bucket is in the same region as the cluster, and warn the user if not.
- [x] Ensure that the bucket is not multi-regional (?)
- [x] Upon cluster deletion, confirm whether user is ok with cleaning out files from chosen bucket. If so, delete all uploads and outputs, but not the bucket itself.

Documentation:
- [x] Add notes about the potential cost premiums for not having the bucket in the same zone as the cluster (or having bucket be "interzone"?) and not deleting files after run ends.
- [x] Include instructions on manually checking the regions of buckets and clusters, and deleting files manually from a bucket.

**Comment by willgraf** [comment]
> Upon cluster deletion, confirm whether user is ok with cleaning out files from chosen bucket. If so, delete all uploads and outputs, but not the bucket itself.

This was resolved by the bucket-monitor update.  Currently, the bucket monitor will crawl the bucket every `INTERVAL` (which is configurable), and remove all files from a set of prefixes ("/uploads" and "/output" by default) that are older than 3 days (also configurable).

This should prevent files from building up and costing extra 💰💰💰.

**Comment by willgraf** [comment]
We can also build a warning in the menu to help notify users that they might end up having interzon egress charges with a multi-regional bucket.

**Comment by willgraf** [comment]
Closed by #329
