### ISSUE TITLE
Confirm HPA Responsiveness

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-console#255]
**Is your feature request related to a problem? Please describe.**
This is a follow-up to issue #187. It would be nice to verfiy, now that we know Prometheus is exporting custom metrics every 15 seconds, that the HPAs are actually utilizing this data fully, i.e., updating every 15 seconds.

**Describe the solution you'd like**
It would be nice to observe via `kubectl get hpa watch`, or any other means, that HPA metrics are indeed updating every 15 seconds.

**Additional context**
The responsiveness of our cluster during scale-up and scale-down is intimately tied to quickly the HPAs can get data from Prometheus. Establishing an upper bound on this feedback loop latency could be helpful for debugging and optimizing performance in the future.

Plus, if we're not utilizing custom metrics data fully right now, we should see a performance increase if we move to a ~15 second Prometheus->HPA feedback cycle.

**Comment by dylanbannon** [comment]
@willgraf points to this page: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/autoscaling/horizontal-pod-autoscaler.md#autoscaling-algorithm
where Kubernetes says that the standard update period for HPAs is 30 seconds. So, we likely aren't getting 15 seconds updates on HPAs right now. It looks like the flag to control this behavior might be passed to a pod in the cluster's control plane, which I think we don't have access to in GKE. Could this be a problem?

Separately, there might also be a flag in `prometheus-adapter` that needs to be set to 15 seconds in order for the whole pipeline to run at a ~15 second latency.

**Comment by willgraf** [comment]
It does indeed seem that HPAs are only evaluated every 30s despite the prometheus 15s intervals.

**Comment by willgraf** [comment]
After watching an 8 GPU cluster start scaling up, I got this HPA output:

<img width="800" alt="Screen Shot 2020-03-31 at 3 10 45 PM" src="https://user-images.githubusercontent.com/7930703/78079903-ee953800-7361-11ea-8a5a-f85a1f70ac80.png">

It looks like the metric changes more frequently than the default 30s intervals, though the actual pod scaling may only happen every 30s.  In any event, the HPA is able to view the changes in the metrics at least as fast as they change, meaning that the 15s prometheus interval can be useful despite not having access to the control plane.

**Comment by willgraf** [comment]
I'm closing this as I think we understand the relationship.

HPAs cannot scale faster than what is defined in the control plane, but the metrics do update based on what is in the Prometheus scrape/evaluation interval.
