### ISSUE TITLE
https://deepcell.org/ is not supported

### ISSUE THREAD

**Issue by Munfred** [vanvalenlab/kiosk-console#266]
![image](https://user-images.githubusercontent.com/12504176/74690416-e9a26d80-5193-11ea-810b-d8a8b9a616d8.png)

**Comment by dylanbannon** [comment]
All jokes aside, this appears to be an issue with the TLS certificates for `https://deepcell.org`. I get a "MOZILLA_PKIX_ERROR_SELF_SIGNED_CERT" error when navigating there in Firefox.

Looking closer, Firefox provides the following, hopefully innocuous, information about the certificate:
![deepcell_cert_cropped](https://user-images.githubusercontent.com/21188071/74690858-61bd6300-5195-11ea-92d8-d36d20ff5e41.png)

I guess this is an issue with the specific deployment we have running behind `deepcell.org`. Is there a flag regarding TLS certificates for ingresses that we need to set?

**Comment by willgraf** [comment]
It looks like [this can be set up through kubectl](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/).  It also seems to me that this is a difference between the turn-key nature of the kiosk versus our impelmentation at deepcell.org.

Regardless, there is no authentication or authorization functionality going on, so no risk of passing unencrypted credentials.  Maybe the image data being uploaded is at risk?

**Comment by willgraf** [comment]
Closed by #357
