### ISSUE TITLE
Reduce Failure Time of Helmfile Deployments

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-console#267]
**Is your feature request related to a problem? Please describe.**
When a helmfile fails to deploy, we have all of our charts configured to wait 10 minutes before retrying. In `gke-helmfile-deployment.sh`, we retry each failing helmfile up to 3 times, meaning that in the worst case, we wait 30 minutes on each failing helmfile. This seems like an exceptionally long time.

**Describe the solution you'd like**
I like the 3 retries policy, but maybe we can reduce the wait time between attempts to 2 minutes 30 seconds, or something like that?

**Describe alternatives you've considered**
Any retry period less than 10 minutes would be an improvement to some extent.

**Comment by willgraf** [comment]
Agreed, sometimes things take an absurdly long time to fail, and waiting 30 minutes for a total failure seems unnecessary.  150s seems like it would not be a perfect blanket answer, as some helmfiles may take longer than others (looking at you, `prometheus`).

Maybe we can set up a new environment variable so during testing we can shorten it?

**Comment by dylanbannon** [comment]
Here's a cool perspective on timing retry loops for HTTP-based failures (like ours): https://cloud.google.com/storage/docs/exponential-backoff

Is there a way to implement this in Helm?

More generally, is it worth implementing this in retries in the rest of the kiosk. The only examples I can think of off the top of my head are in the scripts in `conf/patches`.

**Comment by willgraf** [comment]
I'm not sure about specifically in `helm` or `helmfile`, but our wrapper could potentially use [retry](https://github.com/kamilsk/retry). It looks pretty awesome and comes pre-packaged in geodesic.  I have an open issue to see if we can replace some of our retry loops with it in #206.

**Comment by osterman** [comment]
> Is there a way to implement this in Helm/Helmfile? 

Not really, unless you trigger each helmfile release independently (e.g. with a `--selector`) and wrap that call with `retry` command. E.g. move the batching into a `Makefile`. My gut tells me it might not be worth it?

**Comment by osterman** [comment]
This looks slightly relevant. Could maybe use a postsync hook on error that delays with exponential backoff. 

https://github.com/roboll/helmfile/pull/882

![looks like this though](https://media.giphy.com/media/mYqaRkXyoGbcY/giphy.gif)

**Comment by willgraf** [comment]
`retry` is really nice, but does not play well with our `menu.sh` tail command. The output seems to get spammed to stdout and it's just not very user-friendly. Instead, we can just grow our own retry backoff in the bash script itself.

We are using a helm default of `wait: 600` for every helmfile. This is definitely too long, as a typo in the image tag can lead to 30+ minutes to fail to deploy.

I propose we update each helmfile with its own wait time, with most getting reduced to 120-300s. This should at least halve our deployment time for failed helmfiles.

**Comment by willgraf** [comment]
Closed by #404, which reduces the timeout of nearly all helmfiles and uses an exponential backoff time during helmfile deployment.

Most timeouts are now <= 300s, except for Redis and OpenVPN which both require PVCs which can take time.
