### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-console#272]
**Is your feature request related to a problem? Please describe.**
We currently have a good integration testing framework, but it calls up actual resources in the cloud and so is impractical to run at every commit. We need tests that can be run locally as a precursor to the large-scale tests, which only get run on pull requests.

**Describe the solution you'd like**
We need some tests that can be run locally at every commit that will test individual components of the kiosk. (E.g., helmfile and helm chart linting, or mocking up HTTP responses for local "deployment" of helmfiles.)

First discussed in #268.

**Comment by dylanbannon** [comment]
From discussion with @willgraf in #268:

> >  Last point: while we're here, we might as well add unit tests. My thinking on unit tests is that most of the kiosk's unit tests should probably reside in the sub-repos (kiosk-redis-consumer, etc.). The only thing I can think of that should be in this repo is helmfile and helm chart linting. (Is there anything else I'm missing?)

>A few ideas for some unit tests:
>
>    lint custom helm charts.
>    lint all helmfiles - somehow include checking if docker tags/images exist?
>    menu.sh
>        IDK how to test this, if at all possible. maybe pipe some commands to the menu to assert menu comes up and exits?
>    some kind of kubectl linting for potentially gomplated yaml files
>       conf/patches/redis-exporter-script.yaml
>        conf/patches/hpa.yaml
>        conf/patches/gpu-nodes.yaml
>        conf/addons/ maybe? I'm not sure we use that stuff

>Finally, we have a LOT of logic in conf/tasks, as well as a few scripts in conf/patches. I'm not sure how to test them. I didn't find any sort of gcloud --dry-run option. Maybe we can do some clever stuff with PHONEY targets to skip some make commands during create_all?

**Comment by dylanbannon** [comment]
We have a stub for this feature in the top-level `Makefile`: `test/unit`. `.travis.yml` is already configured to run this target on every push.

**Comment by willgraf** [comment]
In addition to helm/helmfile tests, we could include [prometheus rule tests](https://prometheus.io/docs/prometheus/2.15/configuration/unit_testing_rules/).

**Comment by willgraf** [comment]
Much of the above has been resolved by #326.

Things that are currently not being unit-tested:

- scripts
- patches
- tasks
- accuracy of resources (like redis-exporter-script and prometheus-rules).
- validitiy of the helmfiles (we can build them but am not sure that they work with kubectl)

**Comment by willgraf** [comment]
Closing as this issue is now being tracked in #330
