### ISSUE TITLE
Speed Up Cluster Creation and Destruction

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-console#279]
**Is your feature request related to a problem? Please describe.**
The cluster takes a really long time to create and destroy. Could it be possible to speed it up?

**Describe the solution you'd like**
We should look into ways to speed things up.
1. Could we remove commands? @willgraf has suggested that we could try deleting just the cluster during destruction, but not the node pools, since they might be deleted automatically along with the cluster.
2. Can we parallelize commands? Could the helmfile deployment be done in a series of parallelized stages? Could the same be done with gcloud commands during creation or destruction?

**Comment by dylanbannon** [comment]
This might have some helpful ideas:
https://cloud.google.com/community/tutorials/cloud-functions-async

**Comment by willgraf** [comment]
Deleting the cluster will delete the node-pools inherently. A few minutes can be saved if we just delete the cluster in `make destroy` without deleting the node-pools.

I don't think that there is as simple of a change for cluster creation.

**Comment by willgraf** [comment]
I've set up #407 to skip node-pool destruction during cluster destruction.  This should save several minutes during cluster teardown.

IMO this issue is resolved as much as possible with both #407 and #404

**Comment by willgraf** [comment]
Closed by #404 and #407
