### ISSUE TITLE
Create workflows for Integration Testing

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-console#281]
> > Since we're running integration tests here, it seems like the most "integrated" thing to do would be to run some workflow or series of workflows to in the running cluster before destroying it. What do you think about that?

> Ehh...that does seem like the most robust test, but I'm hesitant to want to bring up a GPU. Let's start off with some light-weight assertions about the state of the cluster, what helm charts are up, what HPAs are up, stuff like that.

> Maybe future work can run through an image through the GPU, but I see this getting complicated as it is dependent on the `tensorflow-serving` model and version of `redis-consumers`, and the input image data.

_Originally posted by @willgraf in https://github.com/vanvalenlab/kiosk/pull/268#issuecomment-593671026_

Let's discuss what the best workflows for integration testing are. Once #268 gets merged in, we'll have a framework that deploys and destroys a cluster automatically; now, we just need to decided what we want to do with that cluster.

**Comment by willgraf** [comment]
Closing as this issue is now being tracked in #330
