### ISSUE TITLE
Update Bug Report Template

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-console#285]
**Is your feature request related to a problem? Please describe.**
When users are having problems with a Kubernetes cluster, there are a lot of things that could possibly go wrong. Since the cluster probably can't stay up until one of us is able to figure out the bug, it's important to get as much information as possible from the user while the cluster is up.

**Describe the solution you'd like**
We should update the bug report template to ask the user for any potentially-relevant information from the cluster.

Let's brainstorm fields we'd like to prompt the user for.

**Comment by dylanbannon** [comment]
`kubectl version`

`kubectl get pods`

`kubectl describe pods [pod_name]` for any pod the user thinks is directly relevant to the issue

**Comment by dylanbannon** [comment]
aces of relevant Prometheus metrics? Logstash metrics of some sort, if relevant?

**Comment by willgraf** [comment]
Closed by #418
