### ISSUE TITLE
prometheus keeps getting evicted, blocking scale-down.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk-console#296]
**Describe the bug**
During a 4GPU benchmarking run, prometheus is getting continually evicted due to memory issues. This prevents the HPAs from recognizing the now 0 workloads, and hundreds of pods stay up instead of getting scaled-down.

After manually scaling down the consumers, prometheus became stable. I think this indicates that the metrics relying on the pod counts are too memory-intensive.

**To Reproduce**
Run a 4 GPU benchmarking job.

**Expected behavior**
I expect prometheus to never get OOMKilled. this removes all previous metrics data.

**Comment by osterman** [comment]
heads up, Prometheus is a memory hog which is probably why you're also seeing the OOM messages. We typically allocate at a minimum of 12-14G ram to it. To lessen the chance of eviction set requests = limit and set a high limit.

**Comment by willgraf** [comment]
Perfect! I had to upgrade the node types we were using to allow for the memory request/limit.  It also seemed that the default `prometheus-adapter` rules were maybe too much for when there were many nodes/pods to monitor.  Maybe one day we can pick and choose the rules for the adapter to export.

In the meantime, upgrading the node type and requesting a LOT of RAM seems to have worked.  (I'm testing with only 8GB and it seems to work fine).

Thanks for the help, @osterman !

**Comment by willgraf** [comment]
We have attempted to resolve this as best as possible with #314. However, Prometheus' memory requirement grows with the number of expected pods. If the memory requirement is greater than the node's limit, Prometheus will not be scheduled.

We recommend using at least `n1-standard-4` as the default node type for clusters of ~8 GPUs to prevent OOM issues.

**Comment by willgraf** [comment]
Closed by #333 which provides users a default option that has enough memory for prometheus, in addition to the small size cluster option.  Also updated troubleshooting docs to include the prometheus memory requirement issue.
