### ISSUE TITLE
Attracting 3rd-party contributors?

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-console#328]
As discussed in #327, long-term, it might be worthwhile to try and attract thrid-party developers to the kiosk. This is more of a philosophical feature request lol.

1) Should we make design decisions in the kiosk project with the aim of eventually attracting third-party developers?

2) If so, what specifically should we do?

**Comment by dylanbannon** [comment]
1) My personal opinion is that expending a small amount of extra effort over a long period of time is probably worth it to attract thrid-party devs.

2) My best guess as to how to attract them is to make the kiosk a pip package. This would involve rewriting some existing code, but it could be done bit-by-bit over a longer period of time. My thinking is that contributors will almost all be scientists and, while docker is a more flexible distribution platofrm for software projects than pip, scientists will almost all have pip already installed and many will even be familiar with the process of writing and maintaining python package; comparatively few scientists will feel as comfortable with docker or bash.

**Comment by willgraf** [comment]
To directly answer the questions in the issue:

1. Yes, we should definitely make this project easy to use for new developers and encourage users to make contributions of their own. However, I would argue we have done so by using standard and open source software in the project, such as Docker, Redis, and kubernetes.

2. Much of our code is already using public standards (k8s, helm, etc.) which lends itself well to 3rd party development. I think a step in making this more open would be to remove the dependency on `gcloud` and move towards being more cloud-agnostic with tools like [terraform](https://www.terraform.io/). 

---

Considering this project does not itself use pip, I think moving it towards a pip package would add another layer of complexity that may discourage new developers. While I have no idea what the scientific community would feel comfortable with, if a user is comfortable maintaining a python library (not just using it via pip) then I would assume using Docker/bash would not be a bridge too far.

**Comment by dylanbannon** [comment]
Let's keep this in mind but, due to off-GitHub discussion of this issue, I'm going to close it. We can revisit it in the future, if it comes up again.
