### ISSUE TITLE
Move Prometheus rules into a separate ConfigMap.

### ISSUE THREAD

**Issue by willgraf** [vanvalenlab/kiosk-console#350]
The Prometheus rules take up a large portion of the `prometheus-operator` helmfile. Maybe we could move these into a separate rule file, and load in a `ConfigMap`.

This could enable better templating via `gomplate` and better enable us to unit test the rules.

_Originally posted by @willgraf in https://github.com/vanvalenlab/kiosk-console/pull/343/review_comment/create_

**Comment by dylanbannon** [comment]
In addition, giving hard-coded constants (like those used in the rules in `conf/helmfile.d/0600.prometheus-operator.yaml`) their own entries in a configmap and then referencing those entries, instead of using the values directly, would aid documentation and future optimization.

**Comment by willgraf** [comment]
I do not think this is supported by the current version of `prometheus-operator` helm chart.

This is still a nice idea, but I will close this for now as it is not supported. We will keep an eye out for future releases that may support it.
