### ISSUE TITLE
Change default name/options for available models

### ISSUE THREAD

**Issue by ngreenwald** [vanvalenlab/kiosk-console#373]
**Is your feature request related to a problem? Please describe.**
Currently the cell-culture based nuclear segmentation model is called 'segmentation' on deepcell.org. This is a bit confusing for outside users, and has caused issues when they try and run multiplex data through the portal. 

**Describe the solution you'd like**
Don't prepopulate the model, and instead require the user to select an appropriate model, in which case they will see that multiplex is one of the options

**Describe alternatives you've considered**
Rename segmentation to something else, like cell_culture_segmentation or something similar to differentiate it from tissue.

**Comment by willgraf** [comment]
Currently, the model is not exposed to the frontend but instead, only a workflow is exposed.

Each of these workflows can be renamed the same way one would [add a new workflow](https://deepcell-kiosk.readthedocs.io/en/master/CUSTOM-JOB.html#connecting-custom-consumers-with-the-kiosk).

**Comment by willgraf** [comment]
Since this issue is really a request for changes to the production environment, and not code changes for the kiosk-console itself, I'm going to close this issue.

Please reach out if you think this should not be closed or for more discussions about settings for the production environment.
