### ISSUE TITLE
Credential authentication fails during GKE configuration 

### ISSUE THREAD

**Issue by msschwartz21** [vanvalenlab/kiosk-console#468]
During the configuration of a GKE cluster from the kiosk console, the user is prompted to follow a link to authenticate their google credentials. The link currently leads to the following error message and further deployment of the cluster is blocked.
<img width="456" alt="Screen Shot 2022-10-25 at 4 27 05 PM" src="https://user-images.githubusercontent.com/20373588/197900932-0962c0e7-df38-4238-8a53-58250f539992.png">

**Comment by willgraf** [comment]
I encountered the same issue and it is coming from the our call to [`gcloud auth login`](https://github.com/vanvalenlab/kiosk-console/blob/30707afa31e1f29d5b317f1e65e3c63a74a48fe2/scripts/gcloud-login.sh#L12). The version installed in our base image appears to be:

```bash
 ✗ : [none] ~ ⨠ gcloud version
Google Cloud SDK 385.0.0
bq 2.0.74
core 2022.05.06
gsutil 5.10
```
and looks like the latest version of our base image [upgrades it to 401.0.0](https://github.com/cloudposse/geodesic/blob/a1fcc37e99a229adff2c4a9f052cf281fc59c2a3/os/alpine/Dockerfile.alpine#L4). I tried updating this and the `build-harness` to the latest, and was able to authenticate with Google.

Here's a PR with the changes: #469

**Comment by willgraf** [comment]
Also, I **strongly** recommend only using the `production` branch for prod deployments, as there is configuration set up there for DNS/security that is required.
