### ISSUE TITLE
Tensorflow-serving won't automatically detect newly-added models

### ISSUE THREAD

**Issue by dylanbannon** [vanvalenlab/kiosk-console#54]
We need to find a way to get Tensorflow Serving to server models that have been uploaded to the storage bucket since tf-serving's creation.

Possibilities:
1) Have the autoscaler watch the S3 bucket and delete all tf-serving pods whenever it detects a new model. (The pods should be immediately restarted.) This would also recommend that we adjust the redis-consumer's fault-tolerance so that it checks whether tf-serving pods exist and just waits patiently or something until they show up. (The idea is to not have the redis-consumer timeout because the tf-serving pods are busy restarting.)

**Comment by osterman** [comment]
Hrm... See this thread https://github.com/tensorflow/serving/issues/537

**Comment by willgraf** [comment]
This has been resolved on the tf-serving side.
